"""Crear tabla categorias_competencia

Revision ID: 174a45afae05
Revises: 3ec2c44e0c7b
Create Date: 2026-01-17 17:16:50.195204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '174a45afae05'
down_revision = '3ec2c44e0c7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_competencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('sexo', sa.String(length=1), nullable=False),
    sa.Column('edad_min', sa.Integer(), nullable=False),
    sa.Column('edad_max', sa.Integer(), nullable=False),
    sa.Column('peso_min', sa.Float(), nullable=True),
    sa.Column('peso_max', sa.Float(), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=True))
        batch_op.alter_column('modalidad',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('observacion',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'categorias_competencia', ['categoria_id'], ['id'])
        batch_op.drop_column('categoria')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('observacion',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
        batch_op.alter_column('modalidad',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20),
               existing_nullable=False)
        batch_op.drop_column('categoria_id')

    op.drop_table('categorias_competencia')
    # ### end Alembic commands ###
