"""Cambiar flexibilidad a enum

Revision ID: 1e9c6c7c6652
Revises: 53ca410b839e
Create Date: 2026-01-16 11:42:03.009727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1e9c6c7c6652'
down_revision = '53ca410b839e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('flexibilidad',
               existing_type=mysql.INTEGER(),
               type_=sa.Enum('Baja', 'Media', 'Alta', name='flexibilidad_emun'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('flexibilidad',
               existing_type=sa.Enum('Baja', 'Media', 'Alta', name='flexibilidad_emun'),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
