"""Agregar sucursal a usuario

Revision ID: 221fd97f2266
Revises: 390e21b3e0c1
Create Date: 2026-01-14 11:12:00.113983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '221fd97f2266'
down_revision = '390e21b3e0c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sucursal_id')

    # ### end Alembic commands ###
