"""create resultados tables

Revision ID: 26abd4062274
Revises: c42799d3627d
Create Date: 2026-02-07 18:16:35.464348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26abd4062274'
down_revision = 'c42799d3627d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resultados_categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torneo_id', sa.Integer(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('modalidad', sa.String(length=10), nullable=False),
    sa.Column('total_competidores', sa.Integer(), nullable=False),
    sa.Column('acta_foto', sa.String(length=255), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_competencia.id'], ),
    sa.ForeignKeyConstraint(['torneo_id'], ['torneos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resultados_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resultado_categoria_id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.Column('nombre_competidor', sa.String(length=200), nullable=True),
    sa.Column('puesto', sa.Integer(), nullable=True),
    sa.Column('medalla_id', sa.Integer(), nullable=True),
    sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('observacion', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.ForeignKeyConstraint(['medalla_id'], ['medallas.id'], ),
    sa.ForeignKeyConstraint(['resultado_categoria_id'], ['resultados_categoria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resultados_detalle')
    op.drop_table('resultados_categoria')
    # ### end Alembic commands ###
