"""add profesor_id to alumnos

Revision ID: 390e21b3e0c1
Revises: 45a5298ec8ec
Create Date: 2026-01-14 10:46:43.542042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '390e21b3e0c1'
down_revision = '45a5298ec8ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profesor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['profesor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('profesor_id')

    # ### end Alembic commands ###
