"""descripcion

Revision ID: 3c4a04416817
Revises: f567c0be6509
Create Date: 2026-01-08 21:44:52.645398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c4a04416817'
down_revision = 'f567c0be6509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('genero',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               type_=sa.String(length=1),
               nullable=False)
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATE(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('genero',
               existing_type=sa.String(length=1),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10),
               nullable=True)

    # ### end Alembic commands ###
