"""crear tabla auditoria

Revision ID: 3e4b94cfa723
Revises: c0aa2749be26
Create Date: 2026-01-20 11:51:20.037765

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e4b94cfa723'
down_revision = 'c0aa2749be26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_nombre', sa.String(length=100), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('datos_antes', sa.JSON(), nullable=True),
    sa.Column('datos_despues', sa.JSON(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_categoria_competencia'))
        batch_op.drop_constraint(batch_op.f('fk_categoria_grado'), type_='foreignkey')

    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('observacion',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.alter_column('observacion',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_categoria_grado'), 'grados', ['grado_id'], ['id'])
        batch_op.create_index(batch_op.f('uq_categoria_competencia'), ['modalidad', 'sexo', 'edad_min', 'edad_max', 'grado_id', 'peso_min', 'peso_max'], unique=True)

    op.drop_table('auditoria')
    # ### end Alembic commands ###
