"""Agregar modalidad a participaciones

Revision ID: 3ec2c44e0c7b
Revises: 56e4fd855a30
Create Date: 2026-01-17 11:37:51.794233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec2c44e0c7b'
down_revision = '56e4fd855a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modalidad', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.drop_column('modalidad')

    # ### end Alembic commands ###
