"""add numero_identidad to alumnos

Revision ID: b6cb28619aab
Revises: 6e9383c22149
Create Date: 2026-02-05 10:00:53.842750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b6cb28619aab'
down_revision = '6e9383c22149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_identidad', sa.String(length=20), nullable=True))

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_asistencias_fecha_sucursal_alumno'))
        batch_op.create_unique_constraint('uq_asistencia_fecha_alumno_sucursal', ['fecha', 'alumno_id', 'sucursal_id'])
        batch_op.drop_constraint(batch_op.f('fk_asistencias_registrado_por'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['registrado_por_id'], ['id'])
        batch_op.drop_column('presente')

    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_categoria_grado'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categorias_competencia', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('fk_categoria_grado'), ['grado_id'], unique=False)

    with op.batch_alter_table('asistencias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('presente', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_asistencias_registrado_por'), 'users', ['registrado_por_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_constraint('uq_asistencia_fecha_alumno_sucursal', type_='unique')
        batch_op.create_index(batch_op.f('uq_asistencias_fecha_sucursal_alumno'), ['fecha', 'sucursal_id', 'alumno_id'], unique=True)

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('numero_identidad')

    # ### end Alembic commands ###
