"""update academias fields

Revision ID: c42799d3627d
Revises: cd25917b67fe
Create Date: 2026-02-07 18:04:10.856262

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c42799d3627d'
down_revision = 'cd25917b67fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academias', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciudad', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))
        batch_op.alter_column('nombre',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('puesto', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('puntaje', sa.Numeric(precision=6, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.drop_column('puntaje')
        batch_op.drop_column('puesto')

    with op.batch_alter_table('academias', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
        batch_op.drop_column('activo')
        batch_op.drop_column('ciudad')

    # ### end Alembic commands ###
