"""add event pricing and event payment fields

Revision ID: cd25917b67fe
Revises: e69bb239b2bc
Create Date: 2026-02-06 16:16:15.693860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd25917b67fe'
down_revision = 'e69bb239b2bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_evento', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('pagado_evento', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('fecha_pago_evento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('metodo_pago_evento', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint('uq_participaciones_torneo_alumno_modalidad', ['torneo_id', 'alumno_id', 'modalidad'])

    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_poomsae', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('precio_combate', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('descuento_ambas', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.drop_column('descuento_ambas')
        batch_op.drop_column('precio_combate')
        batch_op.drop_column('precio_poomsae')

    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participaciones_torneo_alumno_modalidad', type_='unique')
        batch_op.drop_column('metodo_pago_evento')
        batch_op.drop_column('fecha_pago_evento')
        batch_op.drop_column('pagado_evento')
        batch_op.drop_column('valor_evento')

    # ### end Alembic commands ###
