"""Crear tabla grados

Revision ID: d9ac15d345ff
Revises: e643f4664035
Create Date: 2026-01-16 08:39:41.070156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ac15d345ff'
down_revision = 'e643f4664035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('grados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grado_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('peso', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('estatura', sa.Numeric(precision=4, scale=2), nullable=True))
        batch_op.add_column(sa.Column('flexibilidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_ultimo_grado', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('foto', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('foto')
        batch_op.drop_column('fecha_ultimo_grado')
        batch_op.drop_column('flexibilidad')
        batch_op.drop_column('estatura')
        batch_op.drop_column('peso')
        batch_op.drop_column('grado_id')

    op.drop_table('grados')
    # ### end Alembic commands ###
