"""add roles and user_roles

Revision ID: ddc0845b832a
Revises: 2c71761266e2
Create Date: 2026-01-07 15:53:26.128106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ddc0845b832a'
down_revision = '2c71761266e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
