"""Agregar fecha_ingreso a alumno

Revision ID: e643f4664035
Revises: 3a0a1ca3bc69
Create Date: 2026-01-15 15:39:38.953513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e643f4664035'
down_revision = '3a0a1ca3bc69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_ingreso', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_column('fecha_ingreso')

    # ### end Alembic commands ###
