"""add pricing fields to torneos

Revision ID: f02114adee71
Revises: 26abd4062274
Create Date: 2026-02-07 21:21:19.723367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f02114adee71'
down_revision = '26abd4062274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participaciones_alumno_id'), ['alumno_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_modalidad'), ['modalidad'], unique=False)
        batch_op.create_index(batch_op.f('ix_participaciones_torneo_id'), ['torneo_id'], unique=False)
        batch_op.create_unique_constraint('uq_participaciones_torneo_alumno_modalidad', ['torneo_id', 'alumno_id', 'modalidad'])

    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_ambas', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('descuento_ambas')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('torneos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento_ambas', mysql.DECIMAL(precision=10, scale=2), server_default=sa.text("'0.00'"), nullable=False))
        batch_op.drop_column('precio_ambas')

    with op.batch_alter_table('participaciones', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participaciones_torneo_alumno_modalidad', type_='unique')
        batch_op.drop_index(batch_op.f('ix_participaciones_torneo_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_modalidad'))
        batch_op.drop_index(batch_op.f('ix_participaciones_categoria_id'))
        batch_op.drop_index(batch_op.f('ix_participaciones_alumno_id'))

    # ### end Alembic commands ###
