"""Agregar campos a tabla grados

Revision ID: f28f947fccbd
Revises: 1e9c6c7c6652
Create Date: 2026-01-16 13:46:20.612850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f28f947fccbd'
down_revision = '1e9c6c7c6652'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('color', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grados', schema=None) as batch_op:
        batch_op.drop_column('color')
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
