"""create sucursales table

Revision ID: f567c0be6509
Revises: ddc0845b832a
Create Date: 2026-01-08 18:16:00.223580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f567c0be6509'
down_revision = 'ddc0845b832a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('academia_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['academia_id'], ['academias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sucursal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'sucursales', ['sucursal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sucursal_id')

    with op.batch_alter_table('alumnos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('sucursal_id')

    op.drop_table('sucursales')
    op.drop_table('academias')
    # ### end Alembic commands ###
